version: "3.7"

services:
  nexus:
    image: sonatype/nexus3:3.21.1
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    environment:
      TZ: Europe/Berlin
      INSTALL4J_ADD_VM_PARAMS:
        -Xms4g -Xmx4g -XX:MaxDirectMemorySize=6717m
        -Djava.util.prefs.userRoot=/nexus-data/javaprefs

volumes:
  nexus-data:
